# Generated by Django 4.0.6 on 2025-04-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_is_canteen_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lunch_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
