# Generated by Django 4.0.6 on 2025-04-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_lunch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lunch_type',
        ),
    ]
