# Generated by Django 4.0.6 on 2025-04-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_lunch_type'),
        ('canteen', '0010_tblmissedattendance_butcharged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblmissedattendance_butcharged',
            name='date',
        ),
        migrations.AddField(
            model_name='tblmissedattendance_butcharged',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
