# Generated by Django 4.0.6 on 2025-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_remove_tblmissedattendance_butcharged_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmissedattendance_butcharged',
            name='missed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
