# Generated by Django 4.0.6 on 2025-05-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0013_schoolholidaycredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolHolidayCredit',
        ),
    ]
