# Generated by Django 4.0.6 on 2025-05-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_max_class_product_min_class'),
        ('canteen', '0015_monthlyadjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyadjustments',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
