# Generated by Django 4.0.6 on 2025-05-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0016_monthlyadjustments_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyadjustments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='monthlyadjustments',
            name='rate',
        ),
    ]
