# Generated by Django 4.0.6 on 2025-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0017_remove_monthlyadjustments_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyadjustments',
            name='valid_for_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
