# Generated by Django 4.0.6 on 2025-04-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('user', '0008_customer_meal_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_applicable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.discounttable'),
        ),
    ]
