# Generated by Django 4.0.6 on 2025-04-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customer_discount_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='student_class',
        ),
    ]
